//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REST2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebAdminEntities : DbContext
    {
        public WebAdminEntities()
            : base("name=WebAdminEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<attempt> attempts { get; set; }
        public virtual DbSet<candidate> candidates { get; set; }
        public virtual DbSet<paper> papers { get; set; }
        public virtual DbSet<question> questions { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<section> sections { get; set; }
        public virtual DbSet<session> sessions { get; set; }
        public virtual DbSet<staff> staffs { get; set; }
        public virtual DbSet<subsection> subsections { get; set; }
        public virtual DbSet<Table> Tables { get; set; }
    }
}
