//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REST2
{
    using System;
    using System.Collections.Generic;
    
    public partial class paper
    {
        public int paperID { get; set; }
        public Nullable<int> sectionA { get; set; }
        public Nullable<int> sectionB { get; set; }
        public Nullable<int> sectionC { get; set; }
        public Nullable<int> sectionD { get; set; }
    
        public virtual section section { get; set; }
        public virtual section section1 { get; set; }
        public virtual section section2 { get; set; }
        public virtual section section3 { get; set; }
    }
}
