//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IELTSWebAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class attempt
    {
        public int attemptID { get; set; }
        public string record { get; set; }
        public string log { get; set; }
        public Nullable<int> score { get; set; }
        public string grade { get; set; }
    
        public virtual candidate candidate { get; set; }
        public virtual paper paper { get; set; }
        public virtual session session { get; set; }
    }
}
