//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IELTSWebAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class candidate
    {
        public int candidateID { get; set; }
        public string name { get; set; }
        public string studentID { get; set; }
        public string gmailID { get; set; }
        public string eligibility { get; set; }
        public string token { get; set; }
    }
}
