//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IELTSWebAdmin
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WebAdminEntities : DbContext
    {
        public WebAdminEntities()
            : base("name=WebAdminEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<attempt> attempts { get; set; }
        public virtual DbSet<candidate> candidates { get; set; }
        public virtual DbSet<paper> papers { get; set; }
        public virtual DbSet<question> questions { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<section> sections { get; set; }
        public virtual DbSet<session> sessions { get; set; }
        public virtual DbSet<staff> staffs { get; set; }
        public virtual DbSet<subsection> subsections { get; set; }
        public virtual DbSet<Table> Tables { get; set; }
    
        public virtual ObjectResult<questionBysubsection_Result> questionBysubsection(Nullable<int> param1)
        {
            var param1Parameter = param1.HasValue ?
                new ObjectParameter("param1", param1) :
                new ObjectParameter("param1", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<questionBysubsection_Result>("questionBysubsection", param1Parameter);
        }
    
        public virtual ObjectResult<sessionsAfterToday_Result> sessionsAfterToday(Nullable<System.DateTime> param1)
        {
            var param1Parameter = param1.HasValue ?
                new ObjectParameter("param1", param1) :
                new ObjectParameter("param1", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sessionsAfterToday_Result>("sessionsAfterToday", param1Parameter);
        }
    
        public virtual ObjectResult<subsectionBysection_Result> subsectionBysection(Nullable<int> param1)
        {
            var param1Parameter = param1.HasValue ?
                new ObjectParameter("param1", param1) :
                new ObjectParameter("param1", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<subsectionBysection_Result>("subsectionBysection", param1Parameter);
        }
    }
}
