//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IELTSWebAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class paper
    {
        public int paperID { get; set; }
        public byte[] section { get; set; }
    }
}
