//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IELTSWebAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class question
    {
        public int questionID { get; set; }
        public string questionText { get; set; }
        public string answerText { get; set; }
        public Nullable<int> sequence { get; set; }
        public string answerOptions { get; set; }
    
        public virtual subsection subsection { get; set; }
    }
}
