//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IELTSWebAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class role
    {
        public int roleID { get; set; }
        public string roleName { get; set; }
        public Nullable<byte> reports { get; set; }
        public Nullable<byte> marking { get; set; }
        public Nullable<byte> question { get; set; }
    }
}
