//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IELTSWebAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class subsection
    {
        public int subsectionID { get; set; }
        public Nullable<int> totalQuestions { get; set; }
        public string typeOfQuestion { get; set; }
        public byte[] image { get; set; }
        public string sectionText { get; set; }
        public string imageurl { get; set; }
    
        public virtual section section { get; set; }
    }
}
