//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REST
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff
    {
        public int staffID { get; set; }
        public string staffName { get; set; }
        public string gmailID { get; set; }
        public Nullable<int> role { get; set; }
        public string token { get; set; }
    
        public virtual role role1 { get; set; }
    }
}
