//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REST
{
    using System;
    using System.Collections.Generic;
    
    public partial class subsection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public subsection()
        {
            this.questions = new HashSet<question>();
        }
    
        public int subsectionID { get; set; }
        public Nullable<int> totalQuestions { get; set; }
        public string typeOfQuestion { get; set; }
        public Byte[] image { get; set; }
        public Nullable<int> section { get; set; }
        public string sectionText { get; set; }
        public string imageurl { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<question> questions { get; set; }
        public virtual section section1 { get; set; }
    }
}
